### ISSUE TITLE
The new image cannot run normally, prompting "no matching entries in passwd file"

### ISSUE THREAD

**Issue by aaro-n** [federdaemn/docker-anki-sync-server#2]
# docker-compose.yml
```
version: "3.7"

services:

  anki-sync-server-1:
    # https://github.com/federdaemn/anki-sync-server/blob/main/SETUP.md
    image: ghcr.io/federdaemn/anki-sync-server:latest
    container_name: anki-sync-server-1
    restart: unless-stopped
    # these are sample passwords, please change them
    environment:
      - SYNC_USER1=panda:rsfPz4NXELBxmJ
      - SYNC_USER2=penguin:2Qtf5nnsDpsQ3b
    volumes:
      - ./anki-sync-server:/config
        #      - ./12/passwd:/etc/passwd:ro
    ports:
      - 22701:22701

volumes:
  anki-sync-server:
```
# Log
```
www@vultr:~/anki$ docker-compose up
Creating network "anki_default" with the default driver
Creating anki-sync-server-1 ... error

ERROR: for anki-sync-server-1  Cannot start service anki-sync-server-1: unable to find user anki-sync-server: no matching entries in passwd file

ERROR: for anki-sync-server-1  Cannot start service anki-sync-server-1: unable to find user anki-sync-server: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
www@vultr:~/anki$ 
```
# try to solve
Find the following content from the [anki github](https://github.com/ankitects/anki/blob/07909a54e271297a79d9b46f5eb1a02c83d57b58/docs/docker/README.md#:~:text=local/share%3Arw%20%5C-,%2D%2Dvolume%20/etc/passwd%3A/etc/passwd%3Aro,-%5C%0A%20%20%20%20%2D%2Duser%20%24) repository:
```
docker run --rm -it \
    --name anki \
    --volume $HOME/.local/share:$HOME/.local/share:rw \
    --volume /etc/passwd:/etc/passwd:ro \
    --user $(id -u):$(id -g) \
    --volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
    --env DISPLAY=$DISPLAY \
    anki
```
Extract the passwd file from [johngong/anki-sync-server](https://hub.docker.com/r/johngong/anki-sync-server)
**passwd file**
```
www@vultr:~/anki$ cat passwd 
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
ankisync:x:1000:1000::/ankisyncdir:/bin/false
```
Modify docker-compose.yml
```
   .........
    volumes:
      - ./anki-sync-server:/config
      - ./12/passwd:/etc/passwd:ro
    ........
```
Run
```
Creating network "anki_default" with the default driver
Creating anki-sync-server-1 ... error

ERROR: for anki-sync-server-1  Cannot start service anki-sync-server-1: unable to find user anki-sync-server: no matching entries in passwd file

ERROR: for anki-sync-server-1  Cannot start service anki-sync-server-1: unable to find user anki-sync-server: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
```

**Comment by federdaemn** [comment]
Hello,
I pushed a fix to the repository. Can you please try to test this again? I probably can't test this before saturday.

I'm impressed at how much you tried to make it work. The /etc/passwd file was a good idea but anki-sync-server runs on a different user than it runs on <https://hub.docker.com/r/johngong/anki-sync-server> so it doesn't "know" the user. 

Thanks, Frederik

**Comment by federdaemn** [comment]
Nevermind, I get other errors now. I try to resolve this as fast as possible. Thank

**Comment by federdaemn** [comment]
Hello again,

Now, I tried the newest image and for me this worked. I also wrote the false port into the docker-compose.yml file so please have a look at this too. I'm sorry for all the messages but docker and all these things are relatively new for me. Please try out the new image and let me know if it works.

Thanks
Frederik

**Comment by aaro-n** [comment]
The mirror is now running normally. The following are the problems encountered and their solutions:
# Need to adjust files when using folders to store data
docker-compose.yml
```
version: "3.7"

services:

  anki-sync-server-1:
    # https://github.com/federdaemn/anki-sync-server/blob/main/SETUP.md
    image: ghcr.io/federdaemn/anki-sync-server:latest
    container_name: anki-sync-server-1
    restart: unless-stopped
    # these are sample passwords, please change them
    environment:
      - SYNC_USER1=penguin:2Qtf5nnsDpsQ3b
    volumes:
      - ./anki-sync-server:/config
    ports:
      - 27701:27701
```
Use the command `docker-compose up` to create the container and run it.
log
```
www@CN2:~/docker/anki$ ls -al
总用量 12
drwxr-xr-x  2 www www 4096 11月 16 18:00 .
drwxr-xr-x 24 www www 4096 11月 14 07:12 ..
-rw-r--r--  1 www www  433 11月 16 18:00 docker-compose.yml
www@CN2:~/docker/anki$ docker-compose up
Creating network "anki_default" with the default driver
Creating anki-sync-server-1 ... done
Attaching to anki-sync-server-1
anki-sync-server-1    | unable to create server
anki-sync-server-1    | 
anki-sync-server-1    | Caused by these errors (recent errors listed first):
anki-sync-server-1    |   1: creating SYNC_BASE
anki-sync-server-1    |   2: Create "/config/penguin"
anki-sync-server-1    |   3: Permission denied (os error 13)
anki-sync-server-1    | 
www@CN2:~/docker/anki$ ls -al
总用量 16
drwxr-xr-x  3 www  www  4096 11月 16 18:01 .
drwxr-xr-x 24 www  www  4096 11月 14 07:12 ..
drwxr-xr-x  2 root root 4096 11月 16 18:01 anki-sync-server
-rw-r--r--  1 www  www   433 11月 16 18:00 docker-compose.yml
```
Delete container modification file ownership
```
www@CN2:~/docker/anki$ docker-compose down
Stopping anki-sync-server-1 ... done
Removing anki-sync-server-1 ... done
Removing network anki_default
www@CN2:~/docker/anki$ sudo chown nobody:nogroup  anki-sync-server/
www@CN2:~/docker/anki$ ls -al
总用量 16
drwxr-xr-x  3 www    www     4096 11月 16 18:01 .
drwxr-xr-x 24 www    www     4096 11月 14 07:12 ..
drwxr-xr-x  2 nobody nogroup 4096 11月 16 18:01 anki-sync-server
-rw-r--r--  1 www    www      433 11月 16 18:00 docker-compose.yml
```
Run the container again
```
www@CN2:~/docker/anki$ docker-compose up
anki-sync-server-1 is up-to-date
Attaching to anki-sync-server-1
anki-sync-server-1    | 2023-11-16T10:06:07.362207Z  INFO listening addr=0.0.0.0:27701
```
# Cross-platform sync compatibility
Before testing the cross-platform synchronization between android and windows, windows use the latest version, and ankidroid uses AnkiDroid 2.17alpha5. Android and windows can synchronize normally, but the official version of AnkiDroid (AnkiDroid 2.16.5) will have synchronization errors.
AnkiDroid official version synchronization error log:
```
Starting anki-sync-server-1 ... done
Attaching to anki-sync-server-1
anki-sync-server-1    | 2023-11-16T11:49:41.210808Z  INFO listening addr=0.0.0.0:27701
anki-sync-server-1    | 2023-11-16T11:50:23.287820Z  INFO request{uri="/sync/hostKey" ip="117.71.135.70"}: finished elap_ms=0 httpstatus=200
anki-sync-server-1    | 2023-11-16T11:50:28.341482Z  INFO request{uri="/sync/meta" ip="117.71.135.70" uid="penguin" client="" session="41d64baf"}: finished elap_ms=107 httpstatus=200
anki-sync-server-1    | 2023-11-16T11:50:36.314782Z  INFO request{uri="/sync/upload" ip="117.71.135.70" uid="penguin" client="" session=""}: uploaded file was corrupt/failed to open err=DbError { source: DbError { info: "SqliteFailure(Error { code: SystemIoFailure, extended_code: 6410 }, Some(\"disk I/O error\"))", kind: Other } }
anki-sync-server-1    | 2023-11-16T11:50:36.321326Z  INFO request{uri="/sync/upload" ip="117.71.135.70" uid="penguin" client="" session=""}: finished elap_ms=2588 httpstatus=200
```
